{
  'paths':
    {
      '/api/v1/attributes':
        {
          'post':
            {
              'summary': 'Add a new attribute',
              'tags': ['product attributes'],
              'security': [{ 'bearerAuth': [] }],
              'requestBody':
                { '$ref': '#/components/requestBodies/attributeBody' },
              'produces': ['application/json'],
              'responses':
                {
                  '200': { 'description': 'OK' },
                  '400': { 'description': 'Bad request.' },
                },
            },
          'get':
            {
              'summary': 'Get total attributes',
              'tags': ['product attributes'],
              'parameters':
                [
                  {
                    'in': 'query',
                    'name': 'offset',
                    'schema': { 'type': 'integer', 'minimum': 0, 'default': 0 },
                    'required': false,
                    'description': 'The number of items to skip before starting to collect the result set.',
                  },
                  {
                    'in': 'query',
                    'name': 'limit',
                    'schema':
                      {
                        'type': 'integer',
                        'minimum': 1,
                        'maximum': 100,
                        'default': 20,
                      },
                    'required': false,
                    'description': 'The number of items to return.',
                  },
                ],
              'responses':
                {
                  '200': { 'description': 'OK' },
                  '400': { 'description': 'Bad request.' },
                },
            },
        },
      '/api/v1/attributes/{id}':
        {
          'get':
            {
              'summary': 'Get a attribute by ID',
              'tags': ['product attributes'],
              'parameters':
                [
                  {
                    'in': 'path',
                    'name': 'id',
                    'schema': { 'type': 'integer' },
                    'required': true,
                    'description': 'Numeric ID of the attribute to get',
                  },
                ],
              'responses':
                {
                  '200': { 'description': 'OK' },
                  '400': { 'description': 'Bad request.' },
                },
            },
          'put':
            {
              'summary': 'Update a attribute',
              'tags': ['product attributes'],
              'parameters':
                [
                  {
                    'in': 'path',
                    'name': 'id',
                    'schema': { 'type': 'integer' },
                    'required': true,
                    'description': 'Numeric ID of the attribute to get',
                  },
                ],
              'requestBody':
                { '$ref': '#/components/requestBodies/attributeBody' },
              'responses':
                {
                  '200': { 'description': 'OK' },
                  '400': { 'description': 'Bad request.' },
                },
            },
          'delete':
            {
              'summary': 'Delete a attribute',
              'tags': ['product attributes'],
              'parameters':
                [
                  {
                    'in': 'path',
                    'name': 'id',
                    'schema': { 'type': 'integer' },
                    'required': true,
                    'description': 'Numeric ID of the attribute to get',
                  },
                ],
              'requestBody':
                { '$ref': '#/components/requestBodies/attributeBody' },
              'responses':
                {
                  '200': { 'description': 'OK' },
                  '400': { 'description': 'Bad request.' },
                },
            },
        },
    },
  'components':
    {
      'requestBodies':
        {
          'attributeBody':
            {
              'description': 'A JSON object containing attribute information',
              'required': true,
              'content':
                {
                  'application/json':
                    { 'schema': { '$ref': '#/components/schemas/attribute' } },
                },
            },
        },
      'schemas':
        {
          'attribute':
            {
              'title': 'attribute Schemas Information',
              'type': 'object',
              'properties':
                {
                  'name':
                    {
                      'type': 'string',
                      'example': 'Color',
                      'description': 'add attribute name',
                    },
                },
            },
        },
    },
}
