{
  "paths":
    {
      "/v1/products":
        {
          "post":
            {
              "summary": "Add a new Product",
              "tags": ["products"],
              "requestBody":
                { "$ref": "#/components/requestBodies/productBody" },
              "responses":
                {
                  "200": { "description": "OK" },
                  "400": { "description": "Bad request." },
                  "401":
                    {
                      "description": "Authorization information is missing or invalid.",
                    },
                },
            },
          "get":
            {
              "summary": "Get total Products",
              "tags": ["products"],
              "parameters":
                [
                  {
                    "in": "query",
                    "name": "offset",
                    "schema": { "type": "integer", "minimum": 0, "default": 0 },
                    "required": false,
                    "description": "The number of items to skip before starting to collect the result set.",
                  },
                  {
                    "in": "query",
                    "name": "limit",
                    "schema":
                      {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 100,
                        "default": 20,
                      },
                    "required": false,
                    "description": "The number of items to return.",
                  },
                ],
              "responses":
                {
                  "200": { "description": "OK" },
                  "400": { "description": "Bad request." },
                  "401":
                    {
                      "description": "Authorization information is missing or invalid.",
                    },
                },
            },
        },
      "/v1/products/{productId}":
        {
          "get":
            {
              "summary": "Get a Product by ID",
              "tags": ["products"],
              "parameters":
                [
                  {
                    "in": "path",
                    "name": "productId",
                    "schema": { "type": "integer" },
                    "required": true,
                    "description": "Numeric ID of the product to get",
                  },
                ],
              "responses":
                {
                  "200": { "description": "OK" },
                  "400": { "description": "Bad request." },
                  "401":
                    {
                      "description": "Authorization information is missing or invalid.",
                    },
                },
            },
          "patch":
            {
              "summary": "Update a Product",
              "tags": ["products"],
              "parameters":
                [
                  {
                    "in": "path",
                    "name": "productId",
                    "schema": { "type": "integer" },
                    "required": true,
                    "description": "Numeric ID of the product to get",
                  },
                ],
              "requestBody":
                { "$ref": "#/components/requestBodies/productBody" },
              "responses":
                {
                  "200": { "description": "OK" },
                  "400": { "description": "Bad request." },
                  "401":
                    {
                      "description": "Authorization information is missing or invalid.",
                    },
                },
            },
          "delete":
            {
              "summary": "Delete a Product",
              "tags": ["products"],
              "parameters":
                [
                  {
                    "in": "path",
                    "name": "productId",
                    "schema": { "type": "integer" },
                    "required": true,
                    "description": "Numeric ID of the product to get",
                  },
                ],
              "requestBody":
                { "$ref": "#/components/requestBodies/productBody" },
              "responses":
                {
                  "200": { "description": "OK" },
                  "400": { "description": "Bad request." },
                  "401":
                    {
                      "description": "Authorization information is missing or invalid.",
                    },
                },
            },
        },
    },
  "components":
    {
      "requestBodies":
        {
          "productBody":
            {
              "description": "A JSON object containing product information",
              "required": true,
              "content":
                {
                  "application/json":
                    { "schema": { "$ref": "#/components/schemas/product" } },
                },
            },
        },
      "schemas":
        {
          "product":
            {
              "title": "product Schemas Information",
              "type": "object",
              "properties":
                {
                  "name":
                    {
                      "type": "string",
                      "example": "admin",
                      "description": "add product name",
                    },
                  "description":
                    {
                      "type": "string",
                      "example": "this is super admin rule",
                      "description": "add product description",
                    },
                },
            },
        },
    },
}
